[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn api:app -c gunicorn.conf.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
PYTHON_VERSION = "3.11"
